// Vetted Investment Opportunities Data - Sierra Leone
// Merged from CSV with comprehensive details
// All opportunities include ROI/dividend targets and funding status

export interface Investment {
  id: string
  name: string
  category: 'startup' | 'mutual_fund' | 'treasury_bill' | 'government_bond' | 'business'
  description: string
  minInvestment: number
  maxInvestment: number
  roi: number // Annual percentage return
  fundingCurrent: number // Current funding in USD
  fundingGoal: number // Total funding goal
  sector: string
  riskLevel: 'low' | 'medium' | 'high'
  fundingStage: string
  duration: string // Investment period
  status: 'active' | 'closed' | 'ending_soon'
  location?: string
  highlights: string[]
  investorCount?: number
}

export const investments: Investment[] = [
  // === STARTUPS (12 from CSV) ===
  {
    id: 'startup_001',
    name: 'Monime Digital Payments',
    category: 'startup',
    description: 'Mobile money and digital payment platform enabling seamless financial transactions',
    minInvestment: 100,
    maxInvestment: 50000,
    roi: 24.5,
    fundingCurrent: 45000,
    fundingGoal: 200000,
    sector: 'Fintech',
    riskLevel: 'high',
    fundingStage: 'Growth',
    duration: '5 years',
    status: 'active',
    location: 'Freetown',
    highlights: ['Mobile money integration', 'Digital payment solutions', 'Financial inclusion focus'],
    investorCount: 38,
  },
  {
    id: 'startup_002',
    name: 'DirectEd Learning Platform',
    category: 'startup',
    description: 'EdTech platform for online education and skills training with local content',
    minInvestment: 75,
    maxInvestment: 30000,
    roi: 18.0,
    fundingCurrent: 60000,
    fundingGoal: 150000,
    sector: 'Education',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '4 years',
    status: 'active',
    location: 'Freetown/Bo',
    highlights: ['Online education platform', 'Skills training programs', 'Local content focus'],
    investorCount: 42,
  },
  {
    id: 'startup_003',
    name: 'Afro Mobile Tech',
    category: 'startup',
    description: 'Mobile app development and digital solutions for African market',
    minInvestment: 150,
    maxInvestment: 40000,
    roi: 22.0,
    fundingCurrent: 25000,
    fundingGoal: 100000,
    sector: 'Technology',
    riskLevel: 'high',
    fundingStage: 'Early',
    duration: '3 years',
    status: 'active',
    location: 'Freetown',
    highlights: ['Mobile app development', 'Digital solutions', 'African market focus'],
    investorCount: 28,
  },
  {
    id: 'startup_004',
    name: 'Freetown Agro-Processing Hub',
    category: 'startup',
    description: 'Modern cassava processing facility with value-added product development',
    minInvestment: 100,
    maxInvestment: 25000,
    roi: 18.5,
    fundingCurrent: 12500,
    fundingGoal: 50000,
    sector: 'Agriculture',
    riskLevel: 'medium',
    fundingStage: 'Early',
    duration: '3 years',
    status: 'active',
    location: 'Freetown',
    highlights: ['Cassava processing', 'Value-added products', 'Local supply chain'],
    investorCount: 18,
  },
  {
    id: 'startup_005',
    name: 'Sierra Fresh Farms',
    category: 'startup',
    description: 'Organic vegetable farming and distribution network across provinces',
    minInvestment: 200,
    maxInvestment: 35000,
    roi: 16.5,
    fundingCurrent: 35000,
    fundingGoal: 80000,
    sector: 'Agriculture',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '4 years',
    status: 'active',
    location: 'Bo/Kenema',
    highlights: ['Organic farming', 'Distribution network', 'Provincial reach'],
    investorCount: 35,
  },
  {
    id: 'startup_006',
    name: 'Cocoa Export Cooperative',
    category: 'startup',
    description: 'Fair-trade cocoa farming cooperative with international export connections',
    minInvestment: 250,
    maxInvestment: 50000,
    roi: 17.0,
    fundingCurrent: 55000,
    fundingGoal: 120000,
    sector: 'Agriculture',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '5 years',
    status: 'active',
    location: 'Kenema/Kailahun',
    highlights: ['Fair-trade certified', 'International export', 'Cooperative model'],
    investorCount: 52,
  },
  {
    id: 'startup_007',
    name: 'Easy Solar Distribution',
    category: 'startup',
    description: 'Solar energy solutions distributor with pay-as-you-go financing options',
    minInvestment: 50,
    maxInvestment: 20000,
    roi: 12.5,
    fundingCurrent: 75000,
    fundingGoal: 100000,
    sector: 'Energy',
    riskLevel: 'low',
    fundingStage: 'Growth',
    duration: '4 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Solar solutions', 'Pay-as-you-go model', 'Nationwide reach'],
    investorCount: 68,
  },
  {
    id: 'startup_008',
    name: 'Solar Power Distribution',
    category: 'startup',
    description: 'Clean energy solutions with innovative pay-as-you-go pricing model',
    minInvestment: 250,
    maxInvestment: 45000,
    roi: 22.0,
    fundingCurrent: 15000,
    fundingGoal: 75000,
    sector: 'Energy',
    riskLevel: 'high',
    fundingStage: 'Early',
    duration: '4 years',
    status: 'active',
    location: 'Provincial Districts',
    highlights: ['Clean energy', 'Pay-as-you-go', 'Scalable model'],
    investorCount: 22,
  },
  {
    id: 'startup_009',
    name: 'MediConnect Telemedicine',
    category: 'startup',
    description: 'Telemedicine platform connecting patients with qualified healthcare professionals',
    minInvestment: 100,
    maxInvestment: 35000,
    roi: 20.0,
    fundingCurrent: 30000,
    fundingGoal: 90000,
    sector: 'Healthcare',
    riskLevel: 'high',
    fundingStage: 'Growth',
    duration: '4 years',
    status: 'active',
    location: 'Freetown/Provincial',
    highlights: ['Telemedicine services', 'Doctor network', 'Healthcare access'],
    investorCount: 44,
  },
  {
    id: 'startup_010',
    name: 'PharmaSL Supply Chain',
    category: 'startup',
    description: 'Pharmaceutical distribution network ensuring medicine availability nationwide',
    minInvestment: 300,
    maxInvestment: 40000,
    roi: 19.0,
    fundingCurrent: 70000,
    fundingGoal: 150000,
    sector: 'Healthcare',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '5 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Pharmaceutical distribution', 'Supply chain management', 'Medicine availability'],
    investorCount: 55,
  },
  {
    id: 'startup_011',
    name: 'Freetown Beach Resorts',
    category: 'startup',
    description: 'Eco-friendly beach resort development with sustainable tourism practices',
    minInvestment: 500,
    maxInvestment: 60000,
    roi: 25.0,
    fundingCurrent: 120000,
    fundingGoal: 300000,
    sector: 'Tourism',
    riskLevel: 'high',
    fundingStage: 'Development',
    duration: '6 years',
    status: 'active',
    location: 'Western Area',
    highlights: ['Eco-friendly resort', 'Beach development', 'Tourism growth'],
    investorCount: 65,
  },
  {
    id: 'startup_012',
    name: 'Textiles SL Manufacturing',
    category: 'startup',
    description: 'Local textile manufacturing with focus on quality and employment creation',
    minInvestment: 200,
    maxInvestment: 45000,
    roi: 17.5,
    fundingCurrent: 85000,
    fundingGoal: 180000,
    sector: 'Manufacturing',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '5 years',
    status: 'active',
    location: 'Freetown',
    highlights: ['Textile manufacturing', 'Local employment', 'Quality products'],
    investorCount: 48,
  },

  // === TREASURY BILLS (3 from CSV) ===
  {
    id: 'bond_001',
    name: 'Sierra Leone Treasury Bills - 91 Day',
    category: 'treasury_bill',
    description: 'Government-backed short-term securities with 91-day maturity',
    minInvestment: 500,
    maxInvestment: 100000,
    roi: 12.0,
    fundingCurrent: 75000,
    fundingGoal: 100000,
    sector: 'Government Securities',
    riskLevel: 'low',
    fundingStage: 'Issued',
    duration: '91 days',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Government-backed', 'Short-term security', 'Low risk'],
    investorCount: 156,
  },
  {
    id: 'bond_002',
    name: 'Sierra Leone Treasury Bills - 182 Day',
    category: 'treasury_bill',
    description: 'Government-backed short-term securities with 182-day maturity',
    minInvestment: 500,
    maxInvestment: 100000,
    roi: 13.5,
    fundingCurrent: 90000,
    fundingGoal: 150000,
    sector: 'Government Securities',
    riskLevel: 'low',
    fundingStage: 'Issued',
    duration: '182 days',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Government-backed', 'Medium-term security', 'Low risk'],
    investorCount: 142,
  },
  {
    id: 'bond_003',
    name: 'Sierra Leone Treasury Bills - 364 Day',
    category: 'treasury_bill',
    description: 'Government-backed one-year securities with annual maturity',
    minInvestment: 1000,
    maxInvestment: 150000,
    roi: 15.0,
    fundingCurrent: 120000,
    fundingGoal: 200000,
    sector: 'Government Securities',
    riskLevel: 'low',
    fundingStage: 'Issued',
    duration: '364 days',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Government-backed', 'One-year security', 'Low risk'],
    investorCount: 128,
  },

  // === GOVERNMENT BONDS (4 from CSV) ===
  {
    id: 'bond_004',
    name: 'Infrastructure Development Bonds',
    category: 'government_bond',
    description: 'Finance critical road and bridge projects across the nation',
    minInvestment: 1000,
    maxInvestment: 150000,
    roi: 14.0,
    fundingCurrent: 90000,
    fundingGoal: 150000,
    sector: 'Infrastructure',
    riskLevel: 'low',
    fundingStage: 'Active',
    duration: '5 years',
    status: 'active',
    location: 'National Projects',
    highlights: ['Road development', 'Bridge construction', 'Infrastructure growth'],
    investorCount: 98,
  },
  {
    id: 'bond_005',
    name: 'Education Sector Bonds',
    category: 'government_bond',
    description: 'Government bonds for school construction and educational facility development',
    minInvestment: 750,
    maxInvestment: 120000,
    roi: 13.0,
    fundingCurrent: 65000,
    fundingGoal: 120000,
    sector: 'Education',
    riskLevel: 'low',
    fundingStage: 'Active',
    duration: '7 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['School construction', 'Education development', 'Future workforce'],
    investorCount: 85,
  },
  {
    id: 'bond_006',
    name: 'Eurobond - Sierra Leone Growth',
    category: 'government_bond',
    description: 'International government bond for national economic development programs',
    minInvestment: 2000,
    maxInvestment: 200000,
    roi: 16.0,
    fundingCurrent: 150000,
    fundingGoal: 300000,
    sector: 'Government Finance',
    riskLevel: 'low',
    fundingStage: 'Active',
    duration: '10 years',
    status: 'active',
    location: 'International',
    highlights: ['International bond', 'USD denominated', 'Economic growth'],
    investorCount: 110,
  },
  {
    id: 'bond_007',
    name: 'Green Finance Bond',
    category: 'government_bond',
    description: 'Government bond funding environmental and climate-related projects',
    minInvestment: 1500,
    maxInvestment: 180000,
    roi: 14.5,
    fundingCurrent: 95000,
    fundingGoal: 200000,
    sector: 'Environment',
    riskLevel: 'low',
    fundingStage: 'Active',
    duration: '8 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Climate projects', 'Environmental focus', 'Sustainable future'],
    investorCount: 92,
  },

  // === MUTUAL FUNDS (6 from CSV) ===
  {
    id: 'fund_001',
    name: 'Sierra Leone Growth Fund',
    category: 'mutual_fund',
    description: 'Diversified mutual fund of top performing Sierra Leonean companies',
    minInvestment: 100,
    maxInvestment: 150000,
    roi: 16.5,
    fundingCurrent: 140000,
    fundingGoal: 250000,
    sector: 'Diversified Portfolio',
    riskLevel: 'medium',
    fundingStage: 'Active',
    duration: 'Ongoing',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Top companies', 'Diversified portfolio', 'Regular dividends'],
    investorCount: 185,
  },
  {
    id: 'fund_002',
    name: 'Tech Skills Training Fund',
    category: 'mutual_fund',
    description: 'Investment fund supporting coding bootcamps and tech education programs',
    minInvestment: 50,
    maxInvestment: 25000,
    roi: 15.0,
    fundingCurrent: 8000,
    fundingGoal: 25000,
    sector: 'Education',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '2 years',
    status: 'active',
    location: 'Freetown/Bo/Kenema',
    highlights: ['Coding bootcamps', 'Tech skills training', 'Youth empowerment'],
    investorCount: 72,
  },
  {
    id: 'fund_003',
    name: 'Microfinance Growth Fund',
    category: 'mutual_fund',
    description: 'Support small business lending and microfinance institutions',
    minInvestment: 200,
    maxInvestment: 50000,
    roi: 16.5,
    fundingCurrent: 30000,
    fundingGoal: 60000,
    sector: 'Financial Services',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '3 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Small business lending', 'Microfinance support', 'Financial inclusion'],
    investorCount: 94,
  },
  {
    id: 'fund_004',
    name: 'Women Entrepreneurs Fund',
    category: 'mutual_fund',
    description: 'Investment fund supporting and empowering women-owned businesses',
    minInvestment: 100,
    maxInvestment: 60000,
    roi: 14.5,
    fundingCurrent: 42000,
    fundingGoal: 80000,
    sector: 'Social Impact',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '4 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Women entrepreneurs', 'Business empowerment', 'Social impact'],
    investorCount: 108,
  },
  {
    id: 'fund_005',
    name: 'Agriculture Innovation Fund',
    category: 'mutual_fund',
    description: 'Investment in modern farming techniques and agricultural technology',
    minInvestment: 150,
    maxInvestment: 80000,
    roi: 17.0,
    fundingCurrent: 50000,
    fundingGoal: 100000,
    sector: 'Agriculture',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '5 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Modern farming', 'Agricultural tech', 'Yield improvement'],
    investorCount: 87,
  },
  {
    id: 'fund_006',
    name: 'Clean Energy Impact Fund',
    category: 'mutual_fund',
    description: 'Renewable energy fund supporting solar and alternative energy projects',
    minInvestment: 200,
    maxInvestment: 120000,
    roi: 15.5,
    fundingCurrent: 75000,
    fundingGoal: 150000,
    sector: 'Clean Energy',
    riskLevel: 'medium',
    fundingStage: 'Growth',
    duration: '6 years',
    status: 'active',
    location: 'Nationwide',
    highlights: ['Renewable energy', 'Solar projects', 'Environmental impact'],
    investorCount: 102,
  },
]

// Helper functions
export function getInvestmentsByCategory(category: string): Investment[] {
  return investments.filter(inv => inv.category === category)
}

export function getInvestmentsBySector(sector: string): Investment[] {
  return investments.filter(inv => inv.sector === sector)
}

export function getActiveInvestments(): Investment[] {
  return investments.filter(inv => inv.status === 'active')
}

export function getEndingSoonInvestments(): Investment[] {
  return investments.filter(inv => inv.status === 'ending_soon')
}

export function getSortedByROI(): Investment[] {
  return [...investments].sort((a, b) => b.roi - a.roi)
}

export function getSortedByRisk(risk: 'low' | 'medium' | 'high'): Investment[] {
  return investments.filter(inv => inv.riskLevel === risk)
}

export const categories = [
  { id: 'all', label: 'All Opportunities', count: investments.length },
  { id: 'startup', label: 'Vetted Local Startups', count: getInvestmentsByCategory('startup').length },
  { id: 'mutual_fund', label: 'Mutual Funds', count: getInvestmentsByCategory('mutual_fund').length },
  { id: 'treasury_bill', label: 'Treasury Bills', count: getInvestmentsByCategory('treasury_bill').length },
  { id: 'government_bond', label: 'Government Bonds', count: getInvestmentsByCategory('government_bond').length },
]

export const sectors = [
  'All Sectors',
  'Fintech',
  'Education',
  'Technology',
  'Agriculture',
  'Energy',
  'Healthcare',
  'Tourism',
  'Manufacturing',
  'Government Securities',
  'Diversified Portfolio',
  'Financial Services',
  'Social Impact',
  'Clean Energy',
  'Infrastructure',
  'Environment',
]

// Export investments as opportunities for consistency
export const opportunities = investments